INSERT IGNORE INTO `dovecot_users` (`userid`, `domain`, `username`, `loginname`, `password`, `quota_bytes`, `quota_message`, `quota_sieve_bytes`, `quota_sieve_script`, `uid`, `gid`, `home`, `last_login`, `last_login_unix`, `instancename`) VALUES ('1@extern.test', 'extern.test', '1@extern.test', 'test1@extern.test', '{PLAIN}test1', '1000', '0', '0', '0', 'vmail', 'vmail', '/var/vmail/extern.test/1', NULL, NULL, NULL);
INSERT IGNORE INTO `dovecot_usage` (`username`, `storage`, `messages`) VALUES ('1@extern.test', '0', '0');

INSERT IGNORE INTO `dovecot_users` (`userid`, `domain`, `username`, `loginname`, `password`, `quota_bytes`, `quota_message`, `quota_sieve_bytes`, `quota_sieve_script`, `uid`, `gid`, `home`, `last_login`, `last_login_unix`, `instancename`) VALUES ('2@extern.test', 'extern.test', '2@extern.test', 'test2@extern.test', '{PLAIN}test2', '2000', '0', '0', '0', 'vmail', 'vmail', '/var/vmail/extern.test/2', NULL, NULL, NULL);
INSERT IGNORE INTO `dovecot_usage` (`username`, `storage`, `messages`) VALUES ('2@extern.test', '0', '0');

INSERT IGNORE INTO `dovecot_users` (`userid`, `domain`, `username`, `loginname`, `password`, `quota_bytes`, `quota_message`, `quota_sieve_bytes`, `quota_sieve_script`, `uid`, `gid`, `home`, `last_login`, `last_login_unix`, `instancename`) VALUES ('3@extern.test', 'extern.test', '3@extern.test', 'test3@extern.test', '{PLAIN}test3', '3000', '0', '0', '0', 'vmail', 'vmail', '/var/vmail/extern.test/3', NULL, NULL, NULL);
INSERT IGNORE INTO `dovecot_usage` (`username`, `storage`, `messages`) VALUES ('3@extern.test', '0', '0');

INSERT IGNORE INTO `dovecot_users` (`userid`, `domain`, `username`, `loginname`, `password`, `quota_bytes`, `quota_message`, `quota_sieve_bytes`, `quota_sieve_script`, `uid`, `gid`, `home`, `last_login`, `last_login_unix`, `instancename`) VALUES ('4@extern.test', 'extern.test', '4@extern.test', 'test4@extern.test', '{PLAIN}test4', '4000', '0', '0', '0', 'vmail', 'vmail', '/var/vmail/extern.test/4', NULL, NULL, NULL);
INSERT IGNORE INTO `dovecot_usage` (`username`, `storage`, `messages`) VALUES ('4@extern.test', '0', '0');