#!/usr/bin/env php

<?php 

require_once __DIR__ . '/vendor/autoload.php'; 

use Symfony\Component\Console\Application;

use App\ConsoleApplication;
use App\Commands\Docker\DockerUpCommand;
use App\Commands\Docker\DockerStartCommand;
use App\Commands\Docker\DockerStopCommand;
use App\Commands\Docker\DockerDownCommand;
use App\Commands\Docker\DockerCliCommand;
use App\Commands\Docker\DockerPullCommand;
use App\Commands\Docker\DockerLogCommand;
use App\Commands\Docker\DockerWebpackRestartCommand;

use App\Commands\Tine\TineInstallCommand;
use App\Commands\Tine\TineUninstallCommand;
use App\Commands\Tine\TineReinstallCommand;
use App\Commands\Tine\TineTestCommand;
use App\Commands\Tine\TineSetupTestCommand;
use App\Commands\Tine\TineUpdateCommand;
use App\Commands\Tine\TineDemodataCommand;
use App\Commands\Tine\TineCliCommand;
use App\Commands\Tine\TineAwaitDbCommand;
use App\Commands\Tine\TineClearCacheCommand;

use App\Commands\Src\ChangeBranchCommand;
use App\Commands\Src\ComposerCommand;
use App\Commands\Src\NpmCommand;
use App\Commands\Src\NpmInstallCommand;

$app = new ConsoleApplication();

//Docker Commands
$app->add(new DockerUpCommand());
$app->add(new DockerStartCommand());
$app->add(new DockerStopCommand());
$app->add(new DockerDownCommand());
$app->add(new DockerCliCommand());
$app->add(new DockerPullCommand());
$app->add(new DockerLogCommand());
$app->add(new DockerWebpackRestartCommand());

//Tine Commands
$app->add(new TineInstallCommand());
$app->add(new TineUninstallCommand());
$app->add(new TineReinstallCommand());
$app->add(new TineTestCommand());
$app->add(new TineSetupTestCommand());
$app->add(new TineUpdateCommand());
$app->add(new TineDemodataCommand());
$app->add(new TineCliCommand());
$app->add(new TineAwaitDbCommand());
$app->add(new TineClearCacheCommand());

//Src Commands
$app->add(new ChangeBranchCommand());
$app->add(new ComposerCommand());
$app->add(new NpmCommand());
$app->add(new NpmInstallCommand());

$app->run();
