version: '3'
services:
  e2e:
    image: tine20/devsetup-puppeteer:1.0.2
    environment:
        TEST_DOCKER: "true"
        TEST_URL: http://web:10443
        TEST_BROWSER_LANGUAGE: en
    working_dir: /tine20/tests/e2etests
    user: node
    volumes:
      - "./tine20/:/tine20"
    networks:
      - internal_network
