version: '3'
services:
  postfix:
    image: dockerregistry.metaways.net/tine20/docker/postfix:1.0.2
    environment:
      MYSQL_HOST: db
      MYSQL_DB: &postfixdb postfix
      MYSQL_USER: &mysqluser "${MYSQL_USER}"
      MYSQL_PASSWORD: &mysqlpw "${MYSQL_PASSWORD}"
    depends_on:
      - db
    networks:
      - internal_network
      - external_network
    ports:
    - "4025:25"
    #  - "587:587"
    #  - "465:465"

  dovecot:
    image: dockerregistry.metaways.net/tine20/docker/dovecot:1.0.2
    environment:
      MYSQL_HOST: db
      MYSQL_DB: &dovecotdb dovecot
      MYSQL_USER: *mysqluser
      MYSQL_PASSWORD: *mysqlpw
    depends_on:
      - db
    networks:
      - internal_network
      - external_network
    ports:
    - "4143:143"
    #  - "110:110"
    #  - "993:993"
    #  - "995:995"

  mailstack:
    image: dockerregistry.metaways.net/tine20/docker/mailstackcontrol:1.0.5
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: *mysqluser
      MYSQL_PASSWORD: *mysqlpw
      DOVECOT_DATABASE: *dovecotdb
      POSTFIX_DATABASE: *postfixdb
    volumes:
      - ./configs/mailstack/scripts:/scripts
    networks:
      - internal_network

  web:
    environment:
      TINE20_EMAIL_IMAP: "active:true,host:dovecot,port:143,useSystemAccount:1,ssl:tls,verifyPeer:0,backend:dovecot_imap,domain:mail.test,instanceName:tine.test,dovecot_host:db,dovecot_dbname:dovecot,dovecot_username:tine20,dovecot_password:tine20pw,dovecot_uid:vmail,dovecot_gid:vmail,dovecot_home:/var/vmail/%d/%u,dovecot_scheme:SSHA256"
      TINE20_EMAIL_SMTP: "active:true,backend:postfix,hostname:postfix,port:25,ssl:none,auth:none,name:postfix,primarydomain:mail.test,secondarydomains:secondary.test,instanceName:tine.test,postfix_host:db,postfix_dbname:postfix,postfix_username:tine20,postfix_password:tine20pw"
      TINE20_EMAIL_SIEVE: "hostname:dovecot,port:4190,ssl:none"