# this is a override file to add a phpmyadmin container
version: '3'
services:

  pma:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - "4002:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
      MYSQL_USER: "${MYSQL_USER:-tine20}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-tine20pw}"
    networks:
      - external_network
      - internal_network